server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: management
          uri: http://localhost:8081
          predicates:
            - Path=/managements/** 
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/** 
        - id: driver
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/** 
        - id: orderstatus
          uri: http://localhost:8084
          predicates:
            - Path= /orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: management
          uri: http://management:8080
          predicates:
            - Path=/managements/** 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: driver
          uri: http://driver:8080
          predicates:
            - Path=/drivers/** 
        - id: orderstatus
          uri: http://orderstatus:8080
          predicates:
            - Path= /orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
